# docker-compose.yaml

version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - island_bali/.env
    ports:
      - "5432:5432"
  web:
    build: .
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
      - redis
    env_file:
      - island_bali/.env
    entrypoint: >
      sh -c "python manage.py makemigrations
           python manage.py migrate
           python manage.py collectstatic --noinput
           celery -A island_bali worker -l info &
           celery -A island_bali beat -l info &
           exec gunicorn island_bali.wsgi:application -b 0.0.0.0:8000"

  nginx:
    image: nginx:1.21.3-alpine
    restart: always
    ports:
      - "80:80"
      - "8000:8000"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web

  redis:
    image: "redis:latest"
    restart: always
    ports:
      - "6379:6379"


volumes:
  static_value:
  media_value:
  pg_data:

