# Generated by Django 4.2.6 on 2026-07-21 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu_coffee_product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='Владелец корзины'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='addons',
            field=models.ManyToManyField(blank=True, related_name='cart_items', to='menu_coffee_product.addon', verbose_name='Добавки'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.shoppingcart', verbose_name='Корзина'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='flavors',
            field=models.ManyToManyField(blank=True, related_name='cart_items', to='menu_coffee_product.additiveflavors', verbose_name='Вкусовые добавки'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='menu_coffee_product.product', verbose_name='Продукт'),
        ),
    ]
