# Generated by Django 4.2.6

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE cart_cartitem DROP CONSTRAINT IF EXISTS unique_cart_product;",
            reverse_sql="ALTER TABLE cart_cartitem ADD CONSTRAINT unique_cart_product UNIQUE (cart_id, product_id);"
        ),
    ]
