# Generated by Django 4.2.6 on 2026-07-21 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acquiring', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifepayinvoice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lifepay_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterUniqueTogether(
            name='lifepayinvoice',
            unique_together={('transaction_number', 'order')},
        ),
    ]
