# Generated by Django 4.2.6 on 2026-07-21 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acquiring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_coffeeshop', models.CharField(max_length=120, verbose_name='Название кофейни')),
                ('name', models.CharField(choices=[('RussianStandart', 'Русский Стандарт'), ('AlfaBank', 'Альфа Банк'), ('Tinkoff Bank', 'Тиньков Банк')], max_length=100, verbose_name='Эквайринг')),
                ('login', models.CharField(max_length=100, verbose_name='Логин')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Эквайринг',
                'verbose_name_plural': 'Эквайринги',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название города')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='CrmSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('QuickRestoApi', 'QuickRestoApi')], max_length=100, verbose_name='CRM-Система')),
            ],
            options={
                'verbose_name': 'CRM Система',
                'verbose_name_plural': 'CRM Система',
            },
        ),
        migrations.CreateModel(
            name='CoffeeShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=120, verbose_name='Улица')),
                ('building_number', models.CharField(max_length=15, verbose_name='Номер строения')),
                ('email', models.EmailField(help_text='Пожалуйста введите вашу почту чтобы вы могли контролировать отзывы)', max_length=254, verbose_name='Почта для получения плохих отзывов')),
                ('telegram_username', models.CharField(help_text='Введите ваш username из Telegram', max_length=20, verbose_name='Username в Telegram. Пример <@col1ecti0n>')),
                ('telegram_id', models.CharField(blank=True, help_text='Введите ваш id из TelegramПосмотреть id можно в боте @getmyid_bot.', max_length=100, null=True, verbose_name='ID в Telegram. Пример <123456789>')),
                ('time_open', models.TimeField(default='10:00', verbose_name='Время открытия заведения')),
                ('time_close', models.TimeField(default='23:00', verbose_name='Время закрытия заведения')),
                ('crm_email', models.EmailField(help_text='Пожалуйста введите вашу почту чтобы вы могли контролировать отзывы', max_length=254, null=True, verbose_name='Логин для CRM системы')),
                ('crm_password', models.CharField(default='', max_length=20, verbose_name='Пароль для CRM системы')),
                ('crm_layer_name', models.CharField(help_text='Пожалуйста введите название слоя в CRM системе', max_length=100, null=True, verbose_name='Название слоя в CRM системе')),
                ('lifepay_api_key', models.CharField(blank=True, help_text='Ваш API ключ от LifePay', max_length=255, null=True, verbose_name='API ключ LifePay')),
                ('lifepay_login', models.CharField(blank=True, help_text='Логин администратора в LifePay, обычно номер телефона', max_length=20, null=True, verbose_name='Логин LifePay')),
                ('inn', models.CharField(blank=True, help_text='Введите ИНН вашей кофейни', max_length=12, null=True, verbose_name='ИНН')),
                ('phone_number', models.CharField(blank=True, help_text='Введите номер телефона вашей кофейни', max_length=15, null=True, verbose_name='Номер телефона')),
                ('acquiring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee_shop.acquiring', verbose_name='Эквайринг')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee_shop.city', verbose_name='Город')),
                ('crm_system', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='coffee_shop.crmsystem', verbose_name='CRM-Система')),
            ],
            options={
                'verbose_name': 'Кофейня',
                'verbose_name_plural': 'Кофейни',
            },
        ),
    ]
