# Generated by Django 4.2.6 on 2026-09-06 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeshop',
            name='acquiring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coffee_shop.acquiring', verbose_name='Эквайринг'),
        ),
        migrations.AlterField(
            model_name='coffeeshop',
            name='building_number',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Номер строения'),
        ),
        migrations.AlterField(
            model_name='coffeeshop',
            name='crm_email',
            field=models.EmailField(blank=True, default='', help_text='Пожалуйста введите вашу почту чтобы вы могли контролировать отзывы', max_length=254, null=True, verbose_name='Логин для CRM системы'),
        ),
        migrations.AlterField(
            model_name='coffeeshop',
            name='crm_layer_name',
            field=models.CharField(blank=True, default='', help_text='Пожалуйста введите название слоя в CRM системе', max_length=100, null=True, verbose_name='Название слоя в CRM системе'),
        ),
        migrations.AlterField(
            model_name='coffeeshop',
            name='crm_password',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Пароль для CRM системы'),
        ),
        migrations.AlterField(
            model_name='coffeeshop',
            name='crm_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coffee_shop.crmsystem', verbose_name='CRM-Система'),
        ),
        migrations.AlterField(
            model_name='coffeeshop',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Пожалуйста введите вашу почту чтобы вы могли контролировать отзывы)', max_length=254, verbose_name='Почта для получения плохих отзывов'),
        ),
        migrations.AlterField(
            model_name='coffeeshop',
            name='inn',
            field=models.CharField(blank=True, default='', help_text='Введите ИНН вашей кофейни', max_length=30, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='coffeeshop',
            name='lifepay_api_key',
            field=models.CharField(blank=True, default='', help_text='Ваш API ключ от LifePay', max_length=255, null=True, verbose_name='API ключ LifePay'),
        ),
        migrations.AlterField(
            model_name='coffeeshop',
            name='lifepay_login',
            field=models.CharField(blank=True, default='', help_text='Логин администратора в LifePay, обычно номер телефона', max_length=50, null=True, verbose_name='Логин LifePay'),
        ),
        migrations.AlterField(
            model_name='coffeeshop',
            name='phone_number',
            field=models.CharField(blank=True, default='', help_text='Введите номер телефона вашей кофейни', max_length=32, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='coffeeshop',
            name='telegram_id',
            field=models.CharField(blank=True, default='', help_text='Введите ваш id из TelegramПосмотреть id можно в боте @getmyid_bot.', max_length=100, null=True, verbose_name='ID в Telegram. Пример <123456789>'),
        ),
        migrations.AlterField(
            model_name='coffeeshop',
            name='telegram_username',
            field=models.CharField(blank=True, default='', help_text='Введите ваш username из Telegram', max_length=100, verbose_name='Username в Telegram. Пример <@col1ecti0n>'),
        ),
        migrations.AlterField(
            model_name='coffeeshop',
            name='time_close',
            field=models.TimeField(default='22:00', verbose_name='Время закрытия заведения'),
        ),
        migrations.AlterField(
            model_name='coffeeshop',
            name='time_open',
            field=models.TimeField(default='08:00', verbose_name='Время открытия заведения'),
        ),
    ]
