# Generated by Django 4.2.6 on 2026-07-21 14:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('coffee_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewsCoffeeShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation', models.IntegerField(help_text='Оцените заказ от 1 до 5', validators=[django.core.validators.MinValueValidator(1, message='Оценка должна быть не менее 1'), django.core.validators.MaxValueValidator(5, message='Оценка должна быть не более 5')], verbose_name='Оценка заказа')),
                ('very_tasty', models.BooleanField(default=False, verbose_name='Блюда очень вкусные')),
                ('wide_range', models.BooleanField(default=False, verbose_name='Широкий ассортимент')),
                ('nice_prices', models.BooleanField(default=False, verbose_name='Приемлемые цены')),
                ('comments', models.CharField(blank=True, help_text='Оставьте ваш комментарий', max_length=250, verbose_name='Комментарий после выполненного заказа')),
                ('coffee_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee_shop.coffeeshop', verbose_name='Кофейня, в которой был сделан заказ')),
                ('orders', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='orders.orders', verbose_name='Заказ, к которому оставлен отзыв')),
            ],
            options={
                'verbose_name': 'Отзыв пользователя',
                'verbose_name_plural': 'Отзывы пользователей',
            },
        ),
    ]
