# Generated by Django 4.2.6 on 2026-01-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('owner', 'Владелец'), ('admin', 'Администратор'), ('employee', 'Сотрудник'), ('user', 'Пользователь')], default='user', max_length=12, verbose_name='Роль пользователя'),
        ),
    ]
