# Generated by Django 4.2.6 on 2026-09-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_admin_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='Телефон')),
                ('code_hash', models.CharField(max_length=128, verbose_name='Хеш кода')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Попыток ввода')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использован')),
            ],
            options={
                'verbose_name': 'Код подтверждения телефона',
                'verbose_name_plural': 'Коды подтверждения телефона',
                'db_table': 'users_phone_verification',
                'ordering': ('-created_at',),
            },
        ),
    ]
