# Generated by Django 4.2.6 on 2026-07-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название песни')),
                ('author', models.CharField(max_length=255, verbose_name='Имя исполнителя')),
                ('track_id', models.CharField(max_length=100, unique=True, verbose_name='ID трека')),
                ('cover_image_url', models.URLField(verbose_name='URL обложки')),
                ('song', models.FileField(help_text='Загрузите файл песни', upload_to='', verbose_name='Файл песни')),
            ],
            options={
                'verbose_name': 'Музыкальный трек',
                'verbose_name_plural': 'Музыкальные треки',
            },
        ),
    ]
