# Generated by Django 4.2.6 on 2026-07-21 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coffee_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Время начало')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('number_orders_closed', models.PositiveIntegerField(default=0, verbose_name='Закрытые заказы за смену')),
                ('amount_closed_orders', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма заказов за смену')),
                ('status_shift', models.CharField(choices=[('Open', 'Смена открыта'), ('Closed', 'Смена закрыта')], max_length=40, verbose_name='Статус смены')),
            ],
            options={
                'verbose_name': 'Смена',
                'verbose_name_plural': 'Смены',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_of_work', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='coffee_shop.coffeeshop', verbose_name='Место работы')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
