# Generated by Django 4.2.6 on 2026-07-21 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coffee_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Статус активации')),
                ('qr_code', models.CharField(max_length=255, unique=True, verbose_name='Код QR-карты')),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='Изображение QR-кода')),
                ('discount_rate', models.FloatField(default=5.0, verbose_name='Размер скидки (%)')),
                ('coffee_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee_shop.coffeeshop', verbose_name='Кофейня, где действует скидка')),
            ],
            options={
                'verbose_name': 'Скидочная карта',
                'verbose_name_plural': 'Скидочные карты',
            },
        ),
    ]
