# Generated by Django 4.2.6 on 2026-07-21 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bonus_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_card', to=settings.AUTH_USER_MODEL, verbose_name='Владелец карты'),
        ),
    ]
