import {
  User, City, CoffeeShop, Category, Product, Addon, AdditiveFlavor,
  Order, StaffMember, Shift, Review, FranchiseRequest, DiscountCard,
  AdminActivityLog, DashboardKPI, DashboardChartPoint, TopProductItem
} from '../types';

export const mockCities: City[] = [
  { id: 1, name: 'Альметьевск', shops_count: 2 },
  { id: 2, name: 'Казань', shops_count: 3 },
  { id: 3, name: 'Набережные Челны', shops_count: 1 },
];

export const mockCoffeeShops: CoffeeShop[] = [
  {
    id: 1,
    city: 1,
    city_name: 'Альметьевск',
    street: 'ул. Заслонова',
    building_number: '14А',
    email: 'zaslonova@happy-island.coffee',
    telegram_username: '@island_zaslonova',
    telegram_id: '123456789',
    time_open: '08:00',
    time_close: '22:00',
    crm_email: 'crm_zaslonova@island.ru',
    crm_layer_name: 'Основной зал',
    inn: '164401234567',
    phone_number: '+7 (917) 234-56-78',
  },
  {
    id: 2,
    city: 1,
    city_name: 'Альметьевск',
    street: 'ул. Ленина',
    building_number: '32',
    email: 'lenina@happy-island.coffee',
    telegram_username: '@island_lenina',
    telegram_id: '987654321',
    time_open: '08:00',
    time_close: '23:00',
    crm_email: 'crm_lenina@island.ru',
    crm_layer_name: 'Терраса',
    inn: '164401234567',
    phone_number: '+7 (917) 345-67-89',
  },
  {
    id: 3,
    city: 2,
    city_name: 'Казань',
    street: 'ул. Баумана',
    building_number: '44',
    email: 'baumana@happy-island.coffee',
    telegram_username: '@island_kzn_baumana',
    time_open: '07:30',
    time_close: '23:30',
    inn: '165509876543',
    phone_number: '+7 (843) 555-12-34',
  },
];

export const mockFlavors: AdditiveFlavor[] = [
  { id: 1, coffee_shop: 1, name: 'Карамель' },
  { id: 2, coffee_shop: 1, name: 'Ваниль' },
  { id: 3, coffee_shop: 1, name: 'Кокос' },
  { id: 4, coffee_shop: 1, name: 'Лесной орех' },
  { id: 5, coffee_shop: 1, name: 'Соленая карамель' },
  { id: 6, coffee_shop: 1, name: 'Лаванда' },
];

export const mockAddons: Addon[] = [
  {
    id: 1,
    coffee_shop: 1,
    name: 'Сиропы',
    description: 'Ароматные сиропы премиум-класса',
    price: 40,
    flavors: [1, 2, 3, 4, 5, 6],
    flavors_details: mockFlavors,
  },
  {
    id: 2,
    coffee_shop: 1,
    name: 'Растительное молоко (Овсяное/Кокосовое)',
    description: 'Альтернативное молоко',
    price: 60,
  },
  {
    id: 3,
    coffee_shop: 1,
    name: 'Дополнительный эспрессо-шот',
    description: 'Экстра крепость',
    price: 50,
  },
  {
    id: 4,
    coffee_shop: 1,
    name: 'Взбитые сливки и маршмеллоу',
    description: 'Сладкий топпинг',
    price: 45,
  },
];

export const mockCategories: Category[] = [
  { id: 1, coffee_shop: 1, coffee_shop_street: 'ул. Заслонова', name: 'Кофе', which_menu: 'main_menu', products_count: 6 },
  { id: 2, coffee_shop: 1, coffee_shop_street: 'ул. Заслонова', name: 'Авторские напитки', which_menu: 'both', products_count: 4 },
  { id: 3, coffee_shop: 1, coffee_shop_street: 'ул. Заслонова', name: 'Чай и Матча', which_menu: 'main_menu', products_count: 3 },
  { id: 4, coffee_shop: 1, coffee_shop_street: 'ул. Заслонова', name: 'Летнее меню', which_menu: 'season_menu', products_count: 3 },
  { id: 5, coffee_shop: 1, coffee_shop_street: 'ул. Заслонова', name: 'Десерты и выпечка', which_menu: 'main_menu', products_count: 4 },
];

export const mockProducts: Product[] = [
  {
    id: 1,
    coffee_shop: 1,
    coffee_shop_name: 'ул. Заслонова, Альметьевск',
    category: 1,
    category_name: 'Кофе',
    product: 'Капучино',
    price: 190,
    price_s: 160,
    price_m: 190,
    price_l: 230,
    availability: true,
    product_type: 'coffee',
    can_be_hot_and_cold: true,
    temperature_type: 'All',
    which_menu: 'main_menu',
    addons: [1, 2, 3],
    addons_details: [mockAddons[0], mockAddons[1], mockAddons[2]],
  },
  {
    id: 2,
    coffee_shop: 1,
    coffee_shop_name: 'ул. Заслонова, Альметьевск',
    category: 1,
    category_name: 'Кофе',
    product: 'Латте',
    price: 210,
    price_s: 180,
    price_m: 210,
    price_l: 250,
    availability: true,
    product_type: 'coffee',
    can_be_hot_and_cold: true,
    temperature_type: 'All',
    which_menu: 'main_menu',
    addons: [1, 2, 3],
    addons_details: [mockAddons[0], mockAddons[1]],
  },
  {
    id: 3,
    coffee_shop: 1,
    coffee_shop_name: 'ул. Заслонова, Альметьевск',
    category: 1,
    category_name: 'Кофе',
    product: 'Флэт Уайт',
    price: 220,
    price_s: 190,
    price_m: 220,
    price_l: 260,
    availability: true,
    product_type: 'coffee',
    can_be_hot_and_cold: false,
    temperature_type: 'Hot',
    which_menu: 'main_menu',
    addons: [1, 2],
  },
  {
    id: 4,
    coffee_shop: 1,
    coffee_shop_name: 'ул. Заслонова, Альметьевск',
    category: 2,
    category_name: 'Авторские напитки',
    product: 'Бамбл Кофе с апельсином',
    price: 260,
    price_s: 230,
    price_m: 260,
    price_l: 290,
    availability: true,
    product_type: 'coffee',
    can_be_hot_and_cold: false,
    temperature_type: 'Cold',
    which_menu: 'both',
    addons: [1],
  },
  {
    id: 5,
    coffee_shop: 1,
    coffee_shop_name: 'ул. Заслонова, Альметьевск',
    category: 2,
    category_name: 'Авторские напитки',
    product: 'Раф Лаванда-Цитрус',
    price: 270,
    price_s: 240,
    price_m: 270,
    price_l: 310,
    availability: true,
    product_type: 'coffee',
    can_be_hot_and_cold: false,
    temperature_type: 'Hot',
    which_menu: 'main_menu',
    addons: [3],
  },
  {
    id: 6,
    coffee_shop: 1,
    coffee_shop_name: 'ул. Заслонова, Альметьевск',
    category: 3,
    category_name: 'Чай и Матча',
    product: 'Матча Латте на кокосовом',
    price: 250,
    price_s: 220,
    price_m: 250,
    price_l: 290,
    availability: true,
    product_type: 'matcha',
    can_be_hot_and_cold: true,
    temperature_type: 'All',
    which_menu: 'main_menu',
    addons: [1, 2],
  },
  {
    id: 7,
    coffee_shop: 1,
    coffee_shop_name: 'ул. Заслонова, Альметьевск',
    category: 4,
    category_name: 'Летнее меню',
    product: 'Смузи Манго-Маракуйя',
    price: 280,
    price_s: 250,
    price_m: 280,
    price_l: 320,
    availability: false, // In stop list!
    product_type: 'cocktail',
    can_be_hot_and_cold: false,
    temperature_type: 'Cold',
    which_menu: 'season_menu',
  },
  {
    id: 8,
    coffee_shop: 1,
    coffee_shop_name: 'ул. Заслонова, Альметьевск',
    category: 5,
    category_name: 'Десерты и выпечка',
    product: 'Круассан с миндалем',
    price: 180,
    availability: true,
    product_type: 'coffee',
    can_be_hot_and_cold: false,
    temperature_type: 'Hot',
    which_menu: 'main_menu',
  },
];

export const mockUsers: User[] = [
  {
    id: 1,
    login: '+79172340001',
    first_name: 'Рустам',
    last_name: 'Кайдаров',
    full_name: 'Рустам Кайдаров',
    phone_number: '+79172340001',
    email: 'rustam@island.coffee',
    role: 'owner',
    is_active: true,
    is_staff: true,
    is_superuser: true,
    orders_count: 42,
    discount_rate: 15.0,
    cards: [{ id: 1, card_number: '•••• 4242', expiration_date: '12/28' }],
  },
  {
    id: 2,
    login: '+79172340002',
    first_name: 'Алина',
    last_name: 'Смирнова',
    full_name: 'Алина Смирнова',
    phone_number: '+79172340002',
    email: 'alina.admin@island.coffee',
    role: 'admin',
    is_active: true,
    is_staff: true,
    is_superuser: false,
    orders_count: 18,
    discount_rate: 10.0,
    cards: [{ id: 2, card_number: '•••• 8812', expiration_date: '06/27' }],
  },
  {
    id: 3,
    login: '+79172340003',
    first_name: 'Данис',
    last_name: 'Галиев',
    full_name: 'Данис Галиев',
    phone_number: '+79172340003',
    email: 'danis.barista@island.coffee',
    role: 'employee',
    is_active: true,
    is_staff: true,
    is_superuser: false,
    orders_count: 5,
    discount_rate: 5.0,
  },
  {
    id: 4,
    login: '+79991234567',
    first_name: 'Екатерина',
    last_name: 'Иванова',
    full_name: 'Екатерина Иванова',
    phone_number: '+79991234567',
    email: 'ekaterina@gmail.com',
    role: 'user',
    is_active: true,
    is_staff: false,
    is_superuser: false,
    orders_count: 24,
    discount_rate: 7.0,
  },
  {
    id: 5,
    login: '+79274567890',
    first_name: 'Артем',
    last_name: 'Попов',
    full_name: 'Артем Попов',
    phone_number: '+79274567890',
    email: 'artem.popov@mail.ru',
    role: 'user',
    is_active: false, // Blocked user
    is_staff: false,
    is_superuser: false,
    orders_count: 2,
    discount_rate: null,
  },
  {
    id: 6,
    login: '+79051239988',
    first_name: 'Гульназ',
    last_name: 'Мусина',
    full_name: 'Гульназ Мусина',
    phone_number: '+79051239988',
    email: 'gulnaz@yandex.ru',
    role: 'user',
    is_active: true,
    is_staff: false,
    is_superuser: false,
    orders_count: 14,
    discount_rate: 5.0,
  },
];

export const mockOrders: Order[] = [
  {
    id: 1042,
    user: 4,
    user_login: '+79991234567',
    user_full_name: 'Екатерина Иванова',
    city_choose: 1,
    city_name: 'Альметьевск',
    coffee_shop: 1,
    coffee_shop_address: 'ул. Заслонова, Альметьевск',
    staff: 1,
    staff_name: 'Данис Галиев',
    client_comments: 'Пожалуйста, сделайте погорячее',
    staff_comments: '',
    time_is_finish: '2026-08-24 18:15:00',
    status_orders: 'In Progress',
    payment_status: 'Paid',
    full_price: 490,
    client_confirmed: true,
    issued: false,
    created_at: '2026-08-24T17:45:00Z',
    updated_at: '2026-08-24T17:48:00Z',
    items: [
      { id: 1, product: 1, product_name: 'Капучино', size: 'M', amount: 1, addons_names: ['Сиропы'], flavors_names: ['Соленая карамель'], item_total: 230 },
      { id: 2, product: 4, product_name: 'Бамбл Кофе с апельсином', size: 'M', amount: 1, item_total: 260 },
    ],
  },
  {
    id: 1041,
    user: 6,
    user_login: '+79051239988',
    user_full_name: 'Гульназ Мусина',
    city_choose: 1,
    city_name: 'Альметьевск',
    coffee_shop: 1,
    coffee_shop_address: 'ул. Заслонова, Альметьевск',
    staff: 1,
    staff_name: 'Данис Галиев',
    client_comments: 'Без сахара',
    time_is_finish: '2026-08-24 18:05:00',
    status_orders: 'Waiting',
    payment_status: 'Pending',
    full_price: 250,
    client_confirmed: false,
    issued: false,
    created_at: '2026-08-24T17:50:00Z',
    updated_at: '2026-08-24T17:50:00Z',
    items: [
      { id: 3, product: 6, product_name: 'Матча Латте на кокосовом', size: 'M', amount: 1, item_total: 250 },
    ],
  },
  {
    id: 1040,
    user: 1,
    user_login: '+79172340001',
    user_full_name: 'Рустам Кайдаров',
    city_choose: 1,
    city_name: 'Альметьевск',
    coffee_shop: 1,
    coffee_shop_address: 'ул. Заслонова, Альметьевск',
    staff: 1,
    staff_name: 'Данис Галиев',
    status_orders: 'Completed',
    payment_status: 'Paid',
    full_price: 400,
    client_confirmed: true,
    issued: true,
    created_at: '2026-08-24T16:30:00Z',
    updated_at: '2026-08-24T16:45:00Z',
    items: [
      { id: 4, product: 3, product_name: 'Флэт Уайт', size: 'M', amount: 1, item_total: 220 },
      { id: 5, product: 8, product_name: 'Круассан с миндалем', size: 'S', amount: 1, item_total: 180 },
    ],
    review_details: {
      evaluation: 5,
      comments: 'Идеальный кофе и очень быстро!',
      very_tasty: true,
      wide_range: true,
      nice_prices: true,
    },
  },
  {
    id: 1039,
    user: 5,
    user_login: '+79274567890',
    user_full_name: 'Артем Попов',
    city_choose: 1,
    city_name: 'Альметьевск',
    coffee_shop: 1,
    coffee_shop_address: 'ул. Заслонова, Альметьевск',
    status_orders: 'Canceled',
    payment_status: 'Failed',
    cancellation_reason: 'Закончилось миндальное молоко, клиент отказался от замены',
    full_price: 270,
    client_confirmed: false,
    issued: false,
    created_at: '2026-08-24T15:10:00Z',
    updated_at: '2026-08-24T15:15:00Z',
    items: [
      { id: 6, product: 5, product_name: 'Раф Лаванда-Цитрус', size: 'M', amount: 1, item_total: 270 },
    ],
  },
];

export const mockStaff: StaffMember[] = [
  {
    id: 1,
    users: 3,
    user_name: 'Данис Галиев',
    user_phone: '+79172340003',
    place_of_work: 1,
    place_of_work_name: 'ул. Заслонова, Альметьевск',
    current_shift_status: 'Open',
  },
  {
    id: 2,
    users: 2,
    user_name: 'Алина Смирнова',
    user_phone: '+79172340002',
    place_of_work: 2,
    place_of_work_name: 'ул. Ленина, Альметьевск',
    current_shift_status: 'Closed',
  },
];

export const mockShifts: Shift[] = [
  {
    id: 84,
    staff: 1,
    staff_name: 'Данис Галиев',
    coffee_shop_name: 'ул. Заслонова, Альметьевск',
    start_time: '2026-08-24T08:00:00Z',
    end_time: null,
    number_orders_closed: 28,
    amount_closed_orders: 8640.00,
    status_shift: 'Open',
  },
  {
    id: 83,
    staff: 1,
    staff_name: 'Данис Галиев',
    coffee_shop_name: 'ул. Заслонова, Альметьевск',
    start_time: '2026-08-23T08:00:00Z',
    end_time: '2026-08-23T22:00:00Z',
    number_orders_closed: 64,
    amount_closed_orders: 19820.00,
    status_shift: 'Closed',
  },
  {
    id: 82,
    staff: 2,
    staff_name: 'Алина Смирнова',
    coffee_shop_name: 'ул. Ленина, Альметьевск',
    start_time: '2026-08-23T08:00:00Z',
    end_time: '2026-08-23T23:00:00Z',
    number_orders_closed: 78,
    amount_closed_orders: 24500.00,
    status_shift: 'Closed',
  },
];

export const mockReviews: Review[] = [
  {
    id: 1,
    coffee_shop: 1,
    coffee_shop_name: 'ул. Заслонова, Альметьевск',
    user: 1,
    user_name: 'Рустам Кайдаров',
    user_phone: '+79172340001',
    orders: 1040,
    order_price: 400,
    evaluation: 5,
    very_tasty: true,
    wide_range: true,
    nice_prices: true,
    comments: 'Все супер, капучино идеальный, бариста вежливый!',
  },
  {
    id: 2,
    coffee_shop: 1,
    coffee_shop_name: 'ул. Заслонова, Альметьевск',
    user: 4,
    user_name: 'Екатерина Иванова',
    user_phone: '+79991234567',
    orders: 1035,
    order_price: 260,
    evaluation: 4,
    very_tasty: true,
    wide_range: false,
    nice_prices: true,
    comments: 'Бамбл вкусный, но хотелось бы больше авторских сезонных позиций.',
  },
  {
    id: 3,
    coffee_shop: 1,
    coffee_shop_name: 'ул. Заслонова, Альметьевск',
    user: 5,
    user_name: 'Артем Попов',
    user_phone: '+79274567890',
    orders: 1028,
    order_price: 270,
    evaluation: 2,
    very_tasty: false,
    wide_range: false,
    nice_prices: false,
    comments: 'Долго ждал заказ, кофе оказался еле теплым.',
  },
];

export const mockFranchiseRequests: FranchiseRequest[] = [
  {
    id: 1,
    name: 'Ильшат Мухаметшин',
    number_phone: '+7 (927) 888-99-00',
    text: 'Здравствуйте! Планирую открыть кофейню Happy Island в Нижнекамске в ТЦ Олимп. Площадь 35 кв.м. Хочу узнать условия франшизы и стоимость паушального взноса.',
    status: 'new',
    created_at: '2026-08-24T14:20:00Z',
  },
  {
    id: 2,
    name: 'Ольга Белова',
    number_phone: '+7 (917) 111-22-33',
    text: 'Интересует формат острова в бизнес-центре г. Самара. Есть опыт в общепите 3 года.',
    status: 'in_progress',
    created_at: '2026-08-22T11:00:00Z',
  },
];

export const mockDiscountCards: DiscountCard[] = [
  {
    id: 1,
    user: 1,
    user_name: 'Рустам Кайдаров',
    user_phone: '+79172340001',
    is_active: true,
    qr_code: 'CARD_1',
    discount_rate: 15.0,
    coffee_shop: 1,
    coffee_shop_name: 'ул. Заслонова, Альметьевск',
  },
  {
    id: 2,
    user: 4,
    user_name: 'Екатерина Иванова',
    user_phone: '+79991234567',
    is_active: true,
    qr_code: 'CARD_4',
    discount_rate: 7.0,
    coffee_shop: 1,
    coffee_shop_name: 'ул. Заслонова, Альметьевск',
  },
];

export const mockActivityLogs: AdminActivityLog[] = [
  {
    id: 1,
    user: 1,
    user_login: '+79172340001',
    user_name: 'Рустам Кайдаров',
    action: 'STATUS_CHANGE',
    entity_name: 'Orders',
    entity_id: '1042',
    summary: 'Заказ #1042: статус изменен с Waiting на In Progress',
    changes: { old: 'Waiting', new: 'In Progress' },
    ip_address: '178.20.40.50',
    created_at: '2026-08-24T17:48:00Z',
  },
  {
    id: 2,
    user: 2,
    user_login: '+79172340002',
    user_name: 'Алина Смирнова',
    action: 'STATUS_CHANGE',
    entity_name: 'Product',
    entity_id: '7',
    summary: 'Товар Смузи Манго-Маракуйя переведен в стоп-лист',
    changes: { availability: false },
    ip_address: '127.0.0.1',
    created_at: '2026-08-24T16:15:00Z',
  },
  {
    id: 3,
    user: 1,
    user_login: '+79172340001',
    user_name: 'Рустам Кайдаров',
    action: 'LOGIN',
    entity_name: 'CustomUser',
    entity_id: '1',
    summary: 'Вход в панель администратора',
    ip_address: '178.20.40.50',
    created_at: '2026-08-24T15:00:00Z',
  },
];

export const mockDashboardKPI: DashboardKPI = {
  today_revenue: 34850,
  revenue_growth: 14.2,
  today_orders_count: 112,
  today_completed_count: 104,
  today_canceled_count: 3,
  average_check: 335,
  total_users: 1420,
  active_shifts: 4,
};

export const mockChartPoints: DashboardChartPoint[] = [
  { date: '18.08', revenue: 26400, orders_count: 85, completed_count: 82 },
  { date: '19.08', revenue: 28900, orders_count: 92, completed_count: 90 },
  { date: '20.08', revenue: 31200, orders_count: 98, completed_count: 95 },
  { date: '21.08', revenue: 29800, orders_count: 94, completed_count: 91 },
  { date: '22.08', revenue: 38400, orders_count: 124, completed_count: 120 },
  { date: '23.08', revenue: 42100, orders_count: 138, completed_count: 134 },
  { date: '24.08', revenue: 34850, orders_count: 112, completed_count: 104 },
];

export const mockTopProducts: TopProductItem[] = [
  { id: 1, name: 'Капучино (M)', price: 190, category: 'Кофе', sales_count: 142 },
  { id: 2, name: 'Латте (M)', price: 210, category: 'Кофе', sales_count: 118 },
  { id: 4, name: 'Бамбл Кофе с апельсином', price: 260, category: 'Авторские напитки', sales_count: 96 },
  { id: 6, name: 'Матча Латте', price: 250, category: 'Чай и Матча', sales_count: 74 },
  { id: 8, name: 'Круассан с миндалем', price: 180, category: 'Десерты', sales_count: 68 },
];
