# Generated by Django 4.2.6 on 2026-07-21 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coffee_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditiveFlavors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название вкуса')),
                ('coffee_shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additiveflavors_coffe_shop', to='coffee_shop.coffeeshop', verbose_name='Кофейня')),
            ],
            options={
                'verbose_name': 'Вкус добавки',
                'verbose_name_plural': 'Вкусы добавок',
            },
        ),
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название добавки')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание добавки')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Цена')),
                ('coffee_shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addon_coffe_shop', to='coffee_shop.coffeeshop', verbose_name='Кофейня')),
                ('flavors', models.ManyToManyField(blank=True, related_name='additive_flavors', to='menu_coffee_product.additiveflavors', verbose_name='Вкусы добавки')),
            ],
            options={
                'verbose_name': 'Добавка',
                'verbose_name_plural': 'Добавки',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('which_menu', models.CharField(choices=[('main_menu', 'Основное меню'), ('season_menu', 'Сезонное меню'), ('both', 'Оба меню')], default='main_menu', max_length=20, verbose_name='В каком меню находится категория')),
                ('coffee_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='coffee_shop.coffeeshop', verbose_name='Кофейня')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(help_text='Понятное название продукта', max_length=100, unique=True, verbose_name='Продукт')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('availability', models.BooleanField(default=True, verbose_name='Наличие')),
                ('product_type', models.CharField(choices=[('coffee', 'Кофе'), ('ice_cream', 'Мороженое'), ('matcha', 'Матча'), ('tea', 'Чай'), ('cocktail', 'Коктейль'), ('fresh_juice', 'Свежевыжатый сок')], max_length=50, verbose_name='Тип продукта')),
                ('can_be_hot_and_cold', models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=False, verbose_name='Доступен как в горячем, так и в холодном виде?')),
                ('temperature_type', models.CharField(choices=[('Hot', 'Горячий'), ('Cold', 'Холодный'), ('All', 'Все виды')], default='Hot', max_length=4, verbose_name='Тип температуры напитка')),
                ('price_s', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена размера S')),
                ('price_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена размера M')),
                ('price_l', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена размера L')),
                ('which_menu', models.CharField(choices=[('main_menu', 'Основное меню'), ('season_menu', 'Сезонное меню'), ('both', 'Оба меню')], default='main_menu', max_length=20, verbose_name='В каком меню находится продукт')),
                ('addons', models.ManyToManyField(blank=True, to='menu_coffee_product.addon', verbose_name='Добавки')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='menu_coffee_product.category', verbose_name='Категория')),
                ('coffee_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee_shop.coffeeshop', verbose_name='Кофейня')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='SeasonMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seasonal_section', models.CharField(max_length=255, verbose_name='Раздел сезонного меню')),
                ('coffee_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee_shop.coffeeshop', verbose_name='Кофейня')),
                ('products', models.ManyToManyField(to='menu_coffee_product.product', verbose_name='Продукты')),
            ],
            options={
                'verbose_name': 'Сезонное меню',
                'verbose_name_plural': 'Сезонное меню',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(models.F('product'), name='product'),
        ),
    ]
