# Generated by Django 4.2.6 on 2026-09-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_coffee_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product',
            field=models.CharField(help_text='Понятное название продукта', max_length=100, verbose_name='Продукт'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('coffee_shop', 'product'), name='unique_product_per_coffee_shop'),
        ),
    ]
