# Generated by Django 4.2.6 on 2026-07-21 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('coffee_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_photo', models.ImageField(blank=True, null=True, upload_to='check_orders/', verbose_name='Фото чека заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Чек заказа',
                'verbose_name_plural': 'Чеки заказов',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Текст уведомления')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_comments', models.TextField(blank=True, null=True, verbose_name='Комментарий клиента')),
                ('staff_comments', models.TextField(blank=True, null=True, verbose_name='Комментарий сотрудника')),
                ('time_is_finish', models.DateTimeField(blank=True, null=True, verbose_name='Время до получения заказа')),
                ('status_orders', models.CharField(choices=[('New', 'Новый'), ('Waiting', 'Ожидание'), ('In Progress', 'Выполняется'), ('Completed', 'Выполнен'), ('Canceled', 'Отменен')], default='New', max_length=30, verbose_name='Статус заказа')),
                ('payment_status', models.CharField(choices=[('New', 'Новый'), ('Pending', 'Ожидание оплаты'), ('Paid', 'Оплачено'), ('Failed', 'Неудача')], default='New', max_length=30, verbose_name='Статус оплаты')),
                ('receipt_photo', models.ImageField(blank=True, null=True, upload_to='order_receipts/', verbose_name='Фото чека заказа')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('issued', models.BooleanField(default=False, null=True, verbose_name='Оформлен')),
                ('full_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Полная стоимость заказа')),
                ('updated_time', models.DateTimeField(blank=True, null=True, verbose_name='Время обновления заказа')),
                ('cancellation_reason', models.TextField(blank=True, null=True, verbose_name='Причина отмены заказа')),
                ('client_confirmed', models.BooleanField(default=False, verbose_name='Клиент подтвердил заказ')),
                ('is_appreciated', models.BooleanField(default=False, verbose_name='Клиент оценил заказ')),
                ('is_updated', models.BooleanField(default=False, verbose_name='Клиент оценил заказ')),
                ('isThankYouDialogOpen', models.BooleanField(default=False, verbose_name='Диалог благодарности открыт')),
                ('isOrderCancelled', models.BooleanField(default=False, verbose_name='Заказ отменен')),
                ('isTimeChangedDialog', models.BooleanField(default=False, verbose_name='Диалог изменения времени открыт')),
                ('is_used_discount', models.BooleanField(default=False, verbose_name='Скидка применена')),
                ('checkLoaded', models.BooleanField(default=False, null=True, verbose_name='Чек загружен')),
                ('is_testing', models.BooleanField(default=False, verbose_name='Заказ тестовый')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.shoppingcart', verbose_name='Корзина пользователя')),
                ('city_choose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_choose', to='coffee_shop.city', verbose_name='Город в котором заказывают кофе')),
                ('coffee_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coffee_shop_to_orders', to='coffee_shop.coffeeshop', verbose_name='Кофейня на улице')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
