# Generated by Django 4.2.6 on 2026-09-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_state_machine_m1'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='event_seq',
            field=models.PositiveIntegerField(default=0, help_text='Инкрементируется при КАЖДОЙ публикации WebSocket-события по этому заказу — и на бизнес-переходы, и на presentation-изменения (время получения, ack диалогов). Клиент дедуплицирует события по нему. Отличается от version тем, что version — версия бизнес-состояния и оптимистичная блокировка, а event_seq — версия ленты событий.', verbose_name='Порядковый номер realtime-события заказа'),
        ),
    ]
