# Generated by Django 4.2.6 on 2026-09-02 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orders_event_seq'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDialogAck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dialog_key', models.CharField(choices=[('thank_you', 'Спасибо за заказ'), ('canceled', 'Заказ отменён'), ('feedback', 'Оцените заказ (закрыт без оценки)')], max_length=32, verbose_name='Диалог')),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True, verbose_name='Подтверждён')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialog_acks', to='orders.orders', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Подтверждение диалога',
                'verbose_name_plural': 'Подтверждения диалогов',
                'unique_together': {('order', 'dialog_key')},
            },
        ),
    ]
