# Generated by Django 4.2.6 on 2026-09-02 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderdialogack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='isOrderCancelled',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='isThankYouDialogOpen',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='isTimeChangedDialog',
        ),
    ]
